#!/bin/bash

cd /pintos/misc
wget --no-check-certificate https://sourceforge.net/projects/bochs/files/bochs/2.6.11/bochs-2.6.11.tar.gz
sh ./bochs-2.6.11-build.sh /usr/local
rm -f /pintos/misc/bochs-2.6.11.tar.gz
